### PR TITLE
add a special feature

### PR DESCRIPTION
**Pull request by chachyyyy**
i need to fix the ' 's

### CODE REVIEW

**Comment by asbyth** [comment]
chachy why are you dojng this

**Comment by chachyyyy** [comment]
im bored and im back in school soo you know what this means

**Comment by chachyyyy** [comment]
JEBAITED OMEGALUL

**Comment by asbyth** [comment]
i can revoke access anytime i want u gremlin

**Comment by chachyyyy** [comment]
frick u

**Comment by SHARDcoder** [comment]
why is gamora

**Pull request closed without merging**
